name: First workflow

on:
  push:

permissions:
  actions: read
  contents: read
  # ❌ On ne met pas `security-events: write` car on ne veut PAS envoyer à l'onglet "Security" GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'
              - '**/*.html'
              - '**/*.css'
              - '**/*.md'
              - 'screenshots/**'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis (no upload to GitHub Security tab)
        uses: github/codeql-action/analyze@v3
        with:
          upload: false            # ⛔️ IMPORTANT : on désactive l'envoi à GitHub Security
          output: ./codeql-results # 📁 Résultats SARIF stockés localement

      - name: Upload SARIF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: ./codeql-results
