name: First workflow

on:
  push:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'
              - '**/*.html'
              - '**/*.css'
              - '**/*.md'
              - 'screenshots/**'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: ./codeql-results

      - name: Upload CodeQL SARIF result
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: ./codeql-results
