name: Push-to-EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/var/www/html"  # Deploy directly to web root
          ARGS: "-rlgoDzvc --delete"  # Proper rsync arguments

      - name: Configure Apache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # For Amazon Linux (uses httpd instead of apache2)
            sudo yum update -y
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
            
            # Set proper permissions
            sudo chown -R $USER:$USER /var/www/html
            sudo chmod -R 755 /var/www/html
            
            # Restart web server
            sudo systemctl restart httpd
