name: License Scan

on:
  workflow_dispatch:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (si ton projet utilise Node, sinon adapte)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: 'License Scan'
        uses: jmservera/license-finder-action@v0.1.4-alpha
        with:
          permitted-licenses: MIT,Apache-2.0
          approved-dependencies: jquery,bootstrap

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.10.0
        if: always()
        with:
          junit_files: "license_finder_report.xml"

      - name: 'Upload Dependency Review Report'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-finder-report
          path: license_finder_report.xml
