name: Trivy-SCA-analysis

on:
  workflow_dispatch:  # Exécution manuelle depuis GitHub

jobs:
  trivy-sca:
    runs-on: ubuntu-latest
    name: Analyse SCA avec Trivy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan SCA (vulnérabilités + licences) et générer HTML
        run: |
          trivy fs --scanners vuln,license \
            --format template \
            --template "@contrib/html.tpl" \
            -o trivy-report.html \
            --severity HIGH,CRITICAL .

      - name: Upload du rapport HTML
        uses: actions/upload-artifact@v4
        with:
          name: rapport-trivy
          path: trivy-report.html

