name: Analyse Statique avec Semgrep

on:
  workflow_dispatch:  

jobs:
  semgrep-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v3

      - name: ⚡ Installer Semgrep
        run: pip install semgrep

      - name: 🔍 Scanner avec Semgrep (règles OWASP)
        run: semgrep --config p/owasp-top-ten --sarif --output semgrep.sarif

      - name: 📤 Upload du rapport Semgrep
        uses: actions/upload-artifact@v4
        with:
          name: rapport-semgrep
          path: semgrep.sarif
