name: Analyse Statique avec CodeQL

on:
  workflow_dispatch:  

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write

    steps:
      - name: 🧾 Checkout du code
        uses: actions/checkout@v3

      - name: 🧠 Initialiser CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript # You can add others languages using a list

      - name: 🔍 Analyse CodeQL
        uses: github/codeql-action/analyze@v2
        with:
          output: sarif

      - name: 📦 Upload du rapport SARIF
        uses: actions/upload-artifact@v4
        with:
          name: rapport-codeql
          path: '**/*.sarif'  # 🔧 important
